### ISSUE TITLE
Creating a duplicate collection name in a different workspace returns a validation error.

### ISSUE THREAD

**Issue by dalemccrory** [odatahq/bug-tracker#1]
To replicate:
1. Create a collection named "Test" in a workspace named "Test".
2. Create a new workspace named "Test1"
3. Try to create a collection named "Test" and you will not be able to.

![screen shot 2015-06-18 at 1 25 44 pm](https://cloud.githubusercontent.com/assets/548043/8237560/31a4133e-15be-11e5-9f0f-3ccd368a9681.png)

**Comment by erjjones** [comment]
We are investigating this issue. Thanks for letting us know.

**Comment by msdevstep** [comment]
Validation bug is now fixed.
