### ISSUE TITLE
Creating a document with a nested array returns an error...

### ISSUE THREAD

**Issue by dalemccrory** [odatahq/bug-tracker#2]
Here is part of an document that is being created through the "Create Document" UI. The document is failing to be created on the array of Addresses below. 

```` javascript
{
    "Contact": {
        "Address": [
            {
                "AddressType": "OnCampus",
                "Line1": "123 Street",
                "Line2": "",
                "City": "Kabash",
                "State": "IL",
                "PostalCode": "23421",
                "County": "Kendall",
                "CountryCode": "US",
                "IsPrimary": false
            },
            {
                "AddressType": "PermanentStudent",
                "Line1": "2345 Trade-off",
                "Line2": "",
                "City": "Avon",
                "State": "IL",
                "PostalCode": "23421",
                "County": "Hendricks",
                "CountryCode": "US",
                "IsPrimary": false
            }
        ]
    }
}
````

Here is the error that is returned:
Unable to create document: Unsupported type: DynamicClass3. Use the JsonSerializer class to get the object's JSON representation. Path 'Contact.Address'.

**Comment by d1mertz1** [comment]
Hello,
is there any news on this bug?
Thats all somewhat useless if nested arrays do not work.
It would be really nice if it gets fixed.

Thanks

**Comment by msdevstep** [comment]
@d1mertz1 I am currently working on this bug. It was caused by an internal upgrade we performed, I should have a fix for it pushed out shortly. Tests have also been written to prevent this bug in the future. Sorry for any inconvenience this may have caused.

**Comment by d1mertz1** [comment]
@msdevstep 
Sounds good, thanks.

**Comment by msdevstep** [comment]
This issue has been resolved. Creating a document that contains a nested array of complex objects no longer results in an error. Please let me know if you have any questions, or encounter any other unexpected issues.
