### ISSUE TITLE
Complex types with no properties should not show up in the metadata.

### ISSUE THREAD

**Issue by dalemccrory** [odatahq/bug-tracker#3]
From XOData after looking at the metadata for a service deployed ODataHQ:
Following complex type has no properties – metadata should not really have complex types without any properties – however this issue is also already taken care of in XOData *online* and will be deployed within a week in Chrome App – issue was identified with one of the publicly accessible APIs as mentioned in this tweet https://twitter.com/rmtiwari/status/609109873452830720
 
            <ComplexType Name="Program" />
            <ComplexType Name="PriorAcademicAward" />
 
For now you can ask the service provider to remove those unnecessary complex types – or I’ll let you know when new version of Chrome App is deployed  .
However, if you are only interested in making  example queries : then please upload the metadata document that you sent on XOData online ( http://pragmatiqa.com/xodata ) - File upload option is private e.g. not added to OData Directory.

**Comment by msdevstep** [comment]
So I'm looking at the OData specification to try and find some clarification on this. I'm not sure how we can just leave them out if an OData user wants it. The only thing I could think of that they might be using it for is to determine the existence of an empty object to indicate whether some business logic is satisfied. However, more often than not this will probably be a result of a work in progress data model. If this is an issue for your usage of XOData, please refrain from defining complex objects with no properties, as complex objects are designed to contain additional properties.
